Issue 305 3.5
vga91/neo4j-streams pull request #10
Opened 2020-12-22 16:55 UTC by vga91

WIP: rebase issue-272-3.5

2021-02-12 21:15 UTC, conker84 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterBaseIT.kt
> +open class KafkaEventRouterBaseIT {
scusa ma questa classe a che serve?

2021-02-12 22:07 UTC, vga91 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterBaseIT.kt
> +open class KafkaEventRouterBaseIT {
Questa classe contiene parte del codice con il `@Before` , `@After` e `companion object` del `KafkaEventRouterIT()` , che contiene tutta la gestione del `KafkaContainer` e del `GraphDatabaseApi` che mi serviva anche per i test con il logCompaction e quindi ho messo una classe comune per le due e l'ho chiamata così per "coerenza" con la `KafkaEventRouterBaseTSE()` del branch 4.0. Avrei potuto mettere tutto insieme, però sono un bel po' di test

2021-02-22 11:52 UTC, conker84 requested changes
@vga91 guarda i commenti

2021-02-22 11:52 UTC, conker84 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterIT.kt
> +import kotlin.test.*
@vga91 per favore metti Intellij in modo che non succeda questo e ripristina

2021-02-22 11:52 UTC, conker84 commented on producer/src/main/kotlin/streams/Extensions.kt
> +import streams.events.*
ripristina

2021-02-22 11:52 UTC, conker84 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterBaseIT.kt
> +        var graphDatabaseBuilder = TestGraphDatabaseFactory()
vista la modifica per favore rimuovi gli if e metti i `setConfig` dentro i singoli metodi per favore

2021-02-26 11:10 UTC, conker84 approved these changes
Ok sottomettilo grazie!

2021-02-26 11:26 UTC, closed without merging