Fixes #426: Add option to create non-existent nodes at relationship creation
vga91/neo4j-streams pull request #13
Opened 2021-02-18 15:37 UTC by vga91

Fixes #426

2021-02-22 12:09 UTC, conker84 requested changes

2021-02-22 12:09 UTC, conker84 commented on common/src/main/kotlin/streams/service/sink/strategy/CUDIngestionStrategy.kt
> +    private fun getNodeRelOperation(from: NodeRelMetadata) = from.op.toString().toUpperCase()
falla come extension function di `NodeRelMetadata` è più elegante

2021-02-22 12:09 UTC, conker84 commented on common/src/main/kotlin/streams/service/sink/strategy/CUDIngestionStrategy.kt
> +                            val listValidNodesRel = listOf(CUDOperations.merge, CUDOperations.create, CUDOperations.match)
mettile in un companion object!!!!

2021-02-22 12:09 UTC, conker84 commented on common/src/main/kotlin/streams/service/sink/strategy/CUDIngestionStrategy.kt
> +                            val isValidCUDNodesRel = data?.from?.op in listValidNodesRel && data?.to?.op in listValidNodesRel
non si può fare come extension function?

2021-02-22 12:09 UTC, conker84 commented on common/src/main/kotlin/streams/service/sink/strategy/CUDIngestionStrategy.kt
> +                            val isValidCudRel = data?.op?.let { it in listOf(CUDOperations.create, CUDOperations.merge, CUDOperations.update)} ?: false
come sopra

2021-02-24 09:42 UTC, conker84 commented on common/src/main/kotlin/streams/service/sink/strategy/CUDIngestionStrategy.kt
> +    private fun CUDRelationship.isValidCUDRelAndNodes(): Boolean = from.op in LIST_VALID_CUD_NODE_REL && to.op in LIST_VALID_CUD_NODE_REL && op in LIST_VALID_CUD_REL
```suggestion
    private fun CUDRelationship.isValidOperation(): Boolean = from.op in LIST_VALID_CUD_NODE_REL && to.op in LIST_VALID_CUD_NODE_REL && op in LIST_VALID_CUD_REL
```

2021-02-24 09:42 UTC, conker84 commented on common/src/main/kotlin/streams/service/sink/strategy/CUDIngestionStrategy.kt
> +    private fun NodeRelMetadata.getNodeRelOperation() = op.toString().toUpperCase()
```suggestion
    private fun NodeRelMetadata.getOperation() = op.toString().toUpperCase()
```

2021-02-24 12:15 UTC, vga91 commented
@conker84 giocando con i test mi sono accorto di un bug che avveniva quando nella `buildRelCreateStatement()` e nella `buildRelMergeStatement()` del `CudIngestionStrategy` veniva passato uno `startNode` con `MERGE` ed un `endNode` con `MATCH`, perché richiedeva un `WITH` intermedio. Adesso l'ho sistemato

2021-02-26 11:14 UTC, conker84 approved these changes
per favore modifica la documentazione in questo senso e poi sottomettilo

2021-02-26 11:14 UTC, conker84 commented on doc/docs/modules/ROOT/pages/cud-file-format.adoc
> +We can create non-existent nodes at relationship creation/merging, putting `"op": "merge"` in `"from"` and/or `"to"` field, for example:
per favore aggiungi nella documentazione che se non specifichi `op` il default è `merge`

2021-02-26 11:34 UTC, closed without merging