Fixes #305: CDC and Kafka Log Compaction
vga91/neo4j-streams pull request #8
Opened 2020-12-16 14:30 UTC by vga91

Fixes #305

WIP - waiting for #6 and rebase

2020-12-16 18:25 UTC, vga91 commented
@conker84
Non so se sia voluto o meno, ma ho notato che se ad esempio ho un'impostazione tipo: `streams.source.topic.nodes.topic1=Label1:Label2{*}`
`streams.source.topic.nodes.topic2=Label3{*}` 
`streams.source.topic.relationships.topic3=RELAZIONE{*}`

creo delle constraints ad esempio:
`CREATE CONSTRAINT ON (p:Label1) ASSERT p.name IS UNIQUE`
`CREATE CONSTRAINT ON (p:Label2) ASSERT p.surname IS UNIQUE`
`CREATE CONSTRAINT ON (p:Label3) ASSERT p.address IS UNIQUE`

e faccio:
`CREATE (:Label1:Label2 {name:'uno', surname: 'due'})`
`CREATE (:Label3 {address:'Foo'})`
`MATCH (p:Label1:Label2 {name:'uno'}), (pp:Label3 {address:'Foo}) MERGE (p)-[:RELAZIONE]->(pp)`

dal terzo record (della relazione), avrò un `event.payload.start.ids = mapOf("name" to "uno")`,
non dovrebbe invece essere `mapOf("name" to "uno", "surname" to "due")`, cioè la mappa chiave-valore delle proprietà delle due constraint, e non solo di una delle due?

2020-12-17 17:25 UTC, conker84 requested changes

2020-12-17 17:25 UTC, conker84 commented on producer/src/main/kotlin/streams/kafka/KafkaConfiguration.kt
> +                    logCleanupPolicy = config.getOrDefault("log.cleanup.policy", default.logCleanupPolicy),
`log.cleanup.policy` è una vera proprietà di kafka direi di non usarla internamente io la chiamarei `kafka.streams.log.compaction.strategy` i valori vanno bene quelli che hai scelto

2020-12-17 17:25 UTC, conker84 commented on producer/src/main/kotlin/streams/Extensions.kt
> +fun StreamsTransactionEvent.asSourceRecordKey(strategy: String): Any =
trasformalo in when => 

```kotlin
when {
  strategy == TopicConfig.CLEANUP_POLICY_COMPACT -> "${meta.txId + meta.txEventId}-${meta.txEventId}"
  strategy == TopicConfig.CLEANUP_POLICY_DELETE && payload is NodePayload -> // la parte necessaria in caso di nodo
  strategy == TopicConfig.CLEANUP_POLICY_DELETE && payload is RelationshipPayload -> // la parte necessaria in caso di relazione
}
```

2020-12-17 17:25 UTC, conker84 commented on producer/src/main/kotlin/streams/Extensions.kt
> +        }
```suggestion
private fun getNodeConstraintsByLabels(constraints: List<Constraint>,
                                           props: Map<*, *>,
                                           defaultValue: String): Any = constraints.minBy { it.properties.size }
            ?.let { it.properties }
            ?.map { it to props[it] }
            ?.toMap()
            .orEmpty()
            .let {
                if (it.isNotEmpty()) it else defaultValue
            }
```
forse così? ^^^

2020-12-17 17:25 UTC, conker84 commented on producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt
> +    private fun send(producerRecord: ProducerRecord<ByteArray, ByteArray?>) {
questo è necessario?

2020-12-17 17:25 UTC, conker84 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt
> +            NewTopic(topic, 60, 1).configs(mapOf(
io metterei una partizione in modo da essere certo di avere tutti i record li

2020-12-17 17:25 UTC, conker84 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt
> +                    "delete.retention.ms" to "0",
perché?

2020-12-17 17:25 UTC, conker84 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt
> +            assertEquals(1, records.filter{ JSONUtils.readValue<String>(it.key()) == keyRecord }.count())
tutto questo lo puoi fare estrernamente la create

2020-12-18 16:44 UTC, conker84 commented
> @conker84
> Non so se sia voluto o meno, ma ho notato che se ad esempio ho un'impostazione tipo: `streams.source.topic.nodes.topic1=Label1:Label2{*}`
> `streams.source.topic.nodes.topic2=Label3{*}`
> `streams.source.topic.relationships.topic3=RELAZIONE{*}`
> 
> creo delle constraints ad esempio:
> `CREATE CONSTRAINT ON (p:Label1) ASSERT p.name IS UNIQUE`
> `CREATE CONSTRAINT ON (p:Label2) ASSERT p.surname IS UNIQUE`
> `CREATE CONSTRAINT ON (p:Label3) ASSERT p.address IS UNIQUE`
> 
> e faccio:
> `CREATE (:Label1:Label2 {name:'uno', surname: 'due'})`
> `CREATE (:Label3 {address:'Foo'})`
> `MATCH (p:Label1:Label2 {name:'uno'}), (pp:Label3 {address:'Foo}) MERGE (p)-[:RELAZIONE]->(pp)`
> 
> dal terzo record (della relazione), avrò un `event.payload.start.ids = mapOf("name" to "uno")`,
> non dovrebbe invece essere `mapOf("name" to "uno", "surname" to "due")`, cioè la mappa chiave-valore delle proprietà delle due constraint, e non solo di una delle due?

Correggimi se sbaglio ma è giusto no?
Me ne basta una che identifichì univocamente il nodo quelle sono uniche prese singolarmente quindi non c'è bisogno di riportarle tutte no?

2020-12-18 16:47 UTC, conker84 commented on producer/src/main/kotlin/streams/Extensions.kt
> +        }
ho aggiornato l'esempio in modo da ordinare per properties e nome label

2020-12-18 18:42 UTC, vga91 commented on producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt
> +    private fun send(producerRecord: ProducerRecord<ByteArray, ByteArray?>) {
Non credo si possa togliere perché l'Extension `asSourceRecordValue()` può restituire `null`

2020-12-18 19:20 UTC, vga91 commented
> > @conker84
> > Non so se sia voluto o meno, ma ho notato che se ad esempio ho un'impostazione tipo: `streams.source.topic.nodes.topic1=Label1:Label2{*}`
> > `streams.source.topic.nodes.topic2=Label3{*}`
> > `streams.source.topic.relationships.topic3=RELAZIONE{*}`
> > creo delle constraints ad esempio:
> > `CREATE CONSTRAINT ON (p:Label1) ASSERT p.name IS UNIQUE`
> > `CREATE CONSTRAINT ON (p:Label2) ASSERT p.surname IS UNIQUE`
> > `CREATE CONSTRAINT ON (p:Label3) ASSERT p.address IS UNIQUE`
> > e faccio:
> > `CREATE (:Label1:Label2 {name:'uno', surname: 'due'})`
> > `CREATE (:Label3 {address:'Foo'})`
> > `MATCH (p:Label1:Label2 {name:'uno'}), (pp:Label3 {address:'Foo}) MERGE (p)-[:RELAZIONE]->(pp)`
> > dal terzo record (della relazione), avrò un `event.payload.start.ids = mapOf("name" to "uno")`,
> > non dovrebbe invece essere `mapOf("name" to "uno", "surname" to "due")`, cioè la mappa chiave-valore delle proprietà delle due constraint, e non solo di una delle due?
> 
> Correggimi se sbaglio ma è giusto no?
> Me ne basta una che identifichì univocamente il nodo quelle sono uniche prese singolarmente quindi non c'è bisogno di riportarle tutte no?

Ok ok, sì certo la cosa non inficia sul Log Compaction, era più che altro un dubbio sul funzionamento del `payload.ids` perché ho letto `ids` al plurale e pensavo dovesse avere tutte le proprietà estratte dalle constraints.

2021-01-18 09:10 UTC, conker84 commented
@vga91 sottometti grazie mille, se è dipendente da un'altra pr per favore mettila in draft

2021-01-18 14:52 UTC, closed without merging