Fixes #382
vga91/neo4j-streams pull request #9
Opened 2020-12-22 14:28 UTC by vga91

Fixes #382: Unable to add a topic for a label with a specific pattern

2021-01-22 10:37 UTC, conker84 commented
@vga91 per favore aggiungi un test in `RoutingConfigurationTest`

2021-01-22 11:35 UTC, conker84 requested changes

2021-01-22 11:35 UTC, conker84 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterSimpleTSE.kt
> +        db.setConfig("streams.source.topic.nodes.fromTopic.from.neo4j", "Person : Neo4j{*}")
perché?

2021-01-22 11:35 UTC, conker84 commented on producer/src/test/kotlin/streams/RoutingConfigurationTest.kt
> +        routing = RoutingConfigurationFactory.getRoutingConfiguration("topic7", "Label:`labels::label`{ p1,p2,  p3, p4}", EntityType.node) as List<NodeRoutingConfiguration>
ottimo mettine altri con:

```
* `labels::label`:Label:Label1
* :Label``labels::label``:Label1
* :Label`labels::label`:`labels1::label1`:Label1
```

2021-01-22 11:38 UTC, vga91 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterSimpleTSE.kt
> +        db.setConfig("streams.source.topic.nodes.fromTopic.from.neo4j", "Person : Neo4j{*}")
Per far vedere che anche con gli spazi funziona il pattern, ma volendo posso rimetterlo come prima

2021-01-28 11:55 UTC, conker84 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterSimpleTSE.kt
> +        db.setConfig("streams.source.topic.nodes.fromTopic.from.neo4j", "Person : Neo4j{*}")
ma lo fai anche a linea 198 quindi non serve giusto?

2021-01-28 12:00 UTC, vga91 commented on producer/src/test/kotlin/streams/integrations/KafkaEventRouterSimpleTSE.kt
> +        db.setConfig("streams.source.topic.nodes.fromTopic.from.neo4j", "Person : Neo4j{*}")
Sì giusto, lo rimetto come prima

2021-02-01 16:00 UTC, conker84 approved these changes
@vga91 ok sottomettilo

2021-02-04 14:33 UTC, closed without merging